const tributeData = [
    {
        user: 'Ruth Thompson',
        tributename: "ruthson",
        wishlist: "No",
        email: "ruth@gmail.com",
        datecreated: '09-12-2023',
        status: "Active",
        flagged: false,
    },
    {
      user: 'Wale Ojo',
      tributename: "ruthson",
      wishlist: "No",
      email: "waleojogmail.com",
      datecreated: '09-12-2023',
      status: "Inactive",
      flagged: true,
    },
    {
        user: 'Ruth Thompson',
        tributename: "ruthson",
        wishlist: "No",
        email: "ruth@gmail.com",
        datecreated: '09-12-2023',
        status: "Active",
        flagged: false,
    },
    {
        user: 'Wale Ojo',
        tributename: "ruthson",
        wishlist: "No",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: false,
    },
    {
        user: 'Ruth Thompson',
        tributename: "ruthson",
        wishlist: "Yes",
        email: "ruth@gmail.com",
        datecreated: '09-12-2023',
        status: "Active",
        flagged: false,
    },
    {
        user: 'Wale Ojo',
        tributename: "ruthson",
        wishlist: "No",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: true,
    },
    {
        user: 'Wale Ojo',
        tributename: "ruthson",
        wishlist: "No",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: false,
    },
    {
        user: 'Ruth Thompson',
        tributename: "ruthson",
        wishlist: "No",
        email: "ruth@gmail.com",
        datecreated: '09-12-2023',
        status: "Active",
        flagged: true,
    },
    {
        user: 'Wale Ojo',
        tributename: "ruthson",
        wishlist: "No",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: false,
    },
    {
        user: 'Ruth Thompson',
        tributename: "ruthson",
        wishlist: "No",
        email: "ruth@gmail.com",
        datecreated: '09-12-2023',
        status: "Active",
        flagged: true,
    },
    {
        user: 'Wale Ojo',
        tributename: "ruthson",
        wishlist: "No",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: true,
    },
    {
        user: 'Ruth Thompson',
        tributename: "ruthson",
        wishlist: "Yes",
        email: "ruth@gmail.com",
        datecreated: '09-12-2023',
        status: "Active",
        flagged: false,
    },
    {
        user: 'Wale Ojo',
        tributename: "ruthson",
        wishlist: "No",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: true,
    },
    {
        user: 'Wale Ojo',
        tributename: "ruthson",
        wishlist: "No",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: true,
    },
]

export default tributeData;