const wishCardData = [
    {
        user: 'Ruth Thompson',
        wishcardname: "Ola's birthday Card",
        email: "ruth@gmail.com",
        datecreated: '09-12-2023',
        status: "Active",
        flagged: false,
    },
    {
        user: 'Wale Ojo',
        wishcardname: "Funke's birthday Card",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: true,
    },
    {
        user: 'Ruth Thompson',
        wishcardname: "Funke's birthday Card",
        email: "ruth@gmail.com",
        datecreated: '09-12-2023',
        status: "Active",
        flagged: false,
    },
    {
        user: 'Wale Ojo',
        wishcardname: "Ola's birthday Card",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: false,
    },
    {
        user: 'Ruth Thompson',
        wishcardname: "Ola's birthday Card",
        email: "ruth@gmail.com",
        datecreated: '09-12-2023',
        status: "Active",
        flagged: false,
    },
    {
        user: 'Wale Ojo',
        wishcardname: "Ola's birthday Card",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: true,
    },
    {
        user: 'Wale Ojo',
        wishcardname: "Tola's birthday Card",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: false,
    },
    {
        user: 'Ruth Thompson',
        wishcardname: "Tunji's birthday Card",
        email: "ruth@gmail.com",
        datecreated: '09-12-2023',
        status: "Active",
        flagged: true,
    },
    {
        user: 'Wale Ojo',
        wishcardname: "Ola's birthday Card",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: false,
    },
    {
        user: 'Ruth Thompson',
        wishcardname: "Ola's birthday Card",
        email: "ruth@gmail.com",
        datecreated: '09-12-2023',
        status: "Active",
        flagged: true,
    },
    {
        user: 'Wale Ojo',
        wishcardname: "Wale's birthday Card",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: true,
    },
    {
        user: 'Ruth Thompson',
        wishcardname: "Ola's birthday Card",
        email: "ruth@gmail.com",
        datecreated: '09-12-2023',
        status: "Active",
        flagged: false,
    },
    {
        user: 'Wale Ojo',
        wishcardname: "Ola's birthday Card",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: true,
    },
    {
        user: 'Wale Ojo',
        wishcardname: "Folake's birthday Card",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: true,
    },
]

export default wishCardData;