const adminUserlist = [
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Inactive",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Inactive",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Inactive",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Inactive",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Inactive",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Inactive",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Inactive",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Inactive",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Inactive",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Inactive",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Inactive",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Inactive",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Inactive",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Inactive",
        date: "April 12, 2023",
        encrypt: true,
    },
    {
        name: "Munira Adeleke",
        email: "muniraadeleke@gmail.com",
        status:"Active",
        date: "April 12, 2023",
        encrypt: false,
    },
]

export default adminUserlist;