const wishListData = [
    {
        user: 'Ruth Thompson',
        wishlistname: "Ola's birthday List",
        tribute: "No",
        email: "ruth@gmail.com",
        datecreated: '09-12-2023',
        status: "Active",
        flagged: false,
    },
    {
      user: 'Wale Ojo',
      wishlistname: "Ola's birthday List",
      tribute: "No",
      email: "waleojogmail.com",
      datecreated: '09-12-2023',
      status: "Inactive",
      flagged: true,
    },
    {
        user: 'Ruth Thompson',
        wishlistname: "Ola's birthday List",
        tribute: "No",
        email: "ruth@gmail.com",
        datecreated: '09-12-2023',
        status: "Active",
        flagged: false,
    },
    {
        user: 'Wale Ojo',
        wishlistname: "Ola's birthday List",
        tribute: "No",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: false,
    },
    {
        user: 'Ruth Thompson',
        wishlistname: "Ola's birthday List",
        tribute: "Yes",
        email: "ruth@gmail.com",
        datecreated: '09-12-2023',
        status: "Active",
        flagged: false,
    },
    {
        user: 'Wale Ojo',
        wishlistname: "Ola's birthday List",
        tribute: "No",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: true,
    },
    {
        user: 'Wale Ojo',
        wishlistname: "Ola's birthday List",
        tribute: "No",
        email: "waleojogmail.com",
        datecreated: '09-12-2023',
        status: "Inactive",
        flagged: false,
    },
    {
        user: 'Ruth Thompson',
        wishlistname: "Ola's birthday List",
        tribute: "No",
        email: "ruth@gmail.com",
        datecreated: '09-12-2023',
        status: "Active",
        flagged: true,
    },
    {
    user: 'Wale Ojo',
    wishlistname: "Ola's birthday List",
    tribute: "No",
    email: "waleojogmail.com",
    datecreated: '09-12-2023',
    status: "Inactive",
    flagged: false,
    },
    {
    user: 'Ruth Thompson',
    wishlistname: "Ola's birthday List",
    tribute: "No",
    email: "ruth@gmail.com",
    datecreated: '09-12-2023',
    status: "Active",
    flagged: true,
    },
    {
    user: 'Wale Ojo',
    wishlistname: "Ola's birthday List",
    tribute: "No",
    email: "waleojogmail.com",
    datecreated: '09-12-2023',
    status: "Inactive",
    flagged: true,
    },
    {
    user: 'Ruth Thompson',
    wishlistname: "Ola's birthday List",
    tribute: "Yes",
    email: "ruth@gmail.com",
    datecreated: '09-12-2023',
    status: "Active",
    flagged: false,
    },
    {
    user: 'Wale Ojo',
    wishlistname: "Ola's birthday List",
    tribute: "No",
    email: "waleojogmail.com",
    datecreated: '09-12-2023',
    status: "Inactive",
    flagged: true,
    },
    {
    user: 'Wale Ojo',
    wishlistname: "Ola's birthday List",
    tribute: "No",
    email: "waleojogmail.com",
    datecreated: '09-12-2023',
    status: "Inactive",
    flagged: true,
    },
]

export default wishListData;