[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
  for = "*.js"
  [headers.values]
    cache-control = "no-cache"
[[headers]]
  for = "*.css"
  [headers.values]
    cache-control = "no-cache"
