name: Slack Notification

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Send Slack Notification
        run: node .github/scripts/slack-notification.js
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

